# Generated by Django 5.0.2 on 2024-02-26 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='user',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='budgets',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djapi.category'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djapi.category'),
        ),
        migrations.DeleteModel(
            name='BudgetCategory',
        ),
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
    ]
