# Generated by Django 5.0.2 on 2024-03-08 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapi', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
